### ISSUE TITLE
Connecting to a Mosquitto broker on Minishift

### ISSUE THREAD

**Issue by Mack13Podwin** [minishift/minishift#1211]
Hi! I've deployed a Mosquitto app on my Minishift, but I don't know how can I connect to it from outside my cluster (f.e. mosquitto_pub on my Windows).

- Mosquiito image is based on `eclipse-mosquitto` dockerhub

-  I've tried to create a NodePort on my Mosquitto service:

```yaml

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: mosquitto
  type: NodePort
  ports:
  - nodePort: 0
    port: 11883
    protocol: TCP
    targetPort: 1883

```
 but an `Error:  No connection could be made because the target machine actively refused it.` was thrown.

- Now I forwarded port on my VM:
```bash
oc port-forward mosquitto-2-nhl9p 1883:1883
```
and tried sending some data:
```bash
mosquitto_pub -t "t/topic" -m "awesome msg" -p 1883 -h 192.168.99.1
```

`192.168.99.1` is IP of minishift vm.
I also tried permutations of ips and ports taken from `oc describe services` but it also fails.

Besides this I've tried exposing port (`oc expose dc mosquitto --type=LoadBalancer`). This resulted in exposing external port but I couldn't connect to it.

**Comment by gbraad** [comment]
Can you first try to execute the command from within the VM, using `minishift ssh` to try and see if it is not a firewall or other network issue?

If you need to install software in the VM (like the `oc` command, etc), please do so from a `/mnt/sda1/tmp`, or create a subfolder below `/mnt/sda1/`. => Take note of https://docs.openshift.org/latest/minishift/using/troubleshooting.html#root-filesystem-exceeds-overlay-size

**Comment by hferentschik** [comment]
NodePort is the way to go imo. I am not sure about the exact YAML, but have you tried the steps from the documentation https://docs.openshift.org/latest/minishift/openshift/exposing-services.html#nodeport-services?

**Comment by hferentschik** [comment]
_os port-forward_ works of course as well, but is a less permanent solution.

**Comment by Mack13Podwin** [comment]
Hi, this is my final yaml that works.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ingress
  labels:
    app: rabbitmq
spec:
  ports:
    - name: 1883-mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31171
    - name: 15672-console
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31174
  loadBalancerIP: 172.29.0.1
  type: LoadBalancer
  selector:
    app: rabbitmq
  clusterIP: 172.30.194.220

```
