### ISSUE TITLE
S2I javascript : package.json containing git url doesn't work

### ISSUE THREAD

**Issue by robdaems** [minishift/minishift#1483]
Hello,

I'm trying to build a javascript project as source to image.
My code is cloned successfully from git (with a secret), but my package.json contains a dependency to another git repo.
```
  ...
    "vm2": "3.4.6",
    "myutils": "git://git@bitbucket.org/tomyutils",
    "xml2js": "^0.4.17"
  ...
```
During the install minishift can not access the git to install 'myutils'.
How can I provide the secret which can be used during the installation?

Br, Rob

**Comment by GrahamDumpleton** [comment]
Can you try with a HTTPS URL rather than SSH based URL?

Also, is the repository public or private?

**Comment by robdaems** [comment]
Indeed, it's a private repo, that's why I need to use my ssh private key (as a secret).

**Comment by GrahamDumpleton** [comment]
Are you mounting in using a configmap or copying in using some other mechanism, the credentials (ssh private key) the git command in the container would need to access the private repo. Any credentials you add using a source secret for the build configuration are only available to pulling down initial repo, and as far as I know not made available inside of the container for build steps running in the container which want to do a separate git pull off a private repo.

**Comment by robdaems** [comment]
Indeed that's the issue. When I build my docker images manually, via my own Dockerfile, I copy my ssh key temporarily. I copy before the "npm install" and remove it before "npm run start".
I hoped that minishift could do the same when you entered a secret to use.

**Comment by GrahamDumpleton** [comment]
I don't have an exact example showing it handy, but see input secrets at:

* https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#using-secrets-in-the-buildconfig

The idea is that you would create a secret with the private SSH key, and then mount it in under ``/opt/app-root/src/.ssh`` as the default private key. I haven't tried it myself, but I think that would be enough.

**Comment by robdaems** [comment]
I've tried this (I think that's wath you ment):
```
  source:
    git:
      ref: master
      uri: 'git@bitbucket.org:myrepo'
    secrets:
      - destinationDir: /opt/app-root/src/.ssh
        secret:
          name: rob
    sourceSecret:
      name: rob
    type: Git
```
But I still get the error:
```
...
npm ERR! Host key verification failed.
--
  | npm ERR! fatal: Could not read from remote repository.
  | npm ERR!
  | npm ERR! Please make sure you have the correct access rights
  | npm ERR! and the repository exists.
...
```
The reference to git in package.json is clonable via the same ssh key, so using the same secret (rob) should do the trick, but it doesn't.

**Comment by GrahamDumpleton** [comment]
I am not sure you can use same secret as was created by:

```
$ oc secrets new-sshauth sshsecret \
    --ssh-privatekey=$HOME/.ssh/id_rsa
```

You possibly need to use something like:

```
$ oc secrets new bitbucket-ssh-key id_rsa=/some/path/id_rsa
```

and then:

```
  source:
    git:
      ref: master
      uri: 'git@bitbucket.org:myrepo'
    secrets:
      - destinationDir: /opt/app-root/src/.ssh
        secret:
          name: bitbucket-ssh-key
    sourceSecret:
      name: rob
    type: Git
```

The ``id_rsa=`` is import when creating the secret, as the ``id_rsa`` then becomes the name of the file which is created under the ``destinationDir``.

You can test whether things are set up correctly by adding an executable ``.s2i/bin/assemble`` script in your repo which does:

```
#!/bin/bash

set -x
set -eo pipefail

ls -las $HOME/.ssh

exec /usr/libexec/s2i/assemble
```

IOW, list the contents of the directory to see how it set setup and then call original assemble script.

The output will be in the build logs so you can validate it.
