### ISSUE TITLE
Meaningful/Custom Context Names for oc

### ISSUE THREAD

**Issue by phonique** [minishift/minishift#1917]
### General information
I'm attempting to set up a unified environment with minishift and corresponding documentation around it. Documentation would be simplified, if it'd be possible to rely on static naming.
After an initial minishift start, I attempt to set up a named context, users, etc. via oc, but after performing oc login (even with explicit credentials, like `oc login -u=system -p=admin -s=192.168.64.2:8443` or `oc login --context=local -u=developer -p=developer`) a new context, cluster, etc. is created, which does not correspond to the desired naming). In a way this is related to: https://github.com/minishift/minishift/issues/349#issuecomment-323374801
~I don't know, whether this is connected to the fact that oc seems to request a token and create a new user-entry in \~/.kube/config (and prefer this entry), but as I could not find a way to request a token programmatically, I did not pursue this further.~ Placing the token requested by oc for user developer/192-168-64-2:8443 in user developer does not change the behavior.

  * Minishift version: 1.11.0+4459917
  * OS: macOS
  * Hypervisor: xhyve

### Steps to reproduce
Virgin system
  1. minishift start
  2. oc config set-cluster local --server=https://192.168.64.2:8443
  3. oc config set-credentials developer --password=developer
  4. oc config set-context local --cluster=local --user=developer
  5. oc config use-context local
  6. oc login --insecure-skip-tls-verify

### Expected

oc config view

```
apiVersion: v1
clusters:
- cluster:
    server: https://192.168.64.2:8443
  name: local
contexts: []
current-context: "local"
kind: Config
preferences: {}
users:
- name: developer
  user:
    password: developer
- name: system
  user:
    password: admin
```

### Actual
oc login --insecure-skip-tls-verify
```
Authentication required for https://192.168.64.2:8443 (openshift)
Username: developer
Password:
Login successful.
[...]
```

oc config view
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.64.2:8443
  name: 192-168-64-2:8443
- cluster:
    server: https://192.168.64.2:8443
  name: local
contexts:
- context:
    cluster: 192-168-64-2:8443
    namespace: myproject
    user: developer/192-168-64-2:8443
  name: myproject/192-168-64-2:8443/developer
current-context: myproject/192-168-64-2:8443/developer
kind: Config
preferences: {}
users:
- name: developer
  user:
    password: developer
- name: developer/192-168-64-2:8443
  user:
    token: GhsbZXSuzciOIKqUO9P0P7jotlfArBzFQJ4QuFpFpaA
- name: system
  user:
    password: admin
```

### Sidenote

`oc login https://localhost:8443 --username=developer --password=developer` results in
>error: dial tcp [::1]:8443: getsockopt: connection refused - verify you have provided the correct host and port and that the server is currently running.

but I can live with that.
