### ISSUE TITLE
Change limit pod/cpu

### ISSUE THREAD

**Issue by cmoulliard** [minishift/minishift#1971]
Statement: 

"I experiment from time to time such problem on my machine using "oc cluster up"  (openshift origin 3.7.x)

`0/1 nodes are available: 1 Insufficient pods.`

If I look to the to stats generated by the command "oc get node localhost", then I can see that the limit of the pods created has been reached.

As the convention followed by openshift is to limit the number of the pods "available" to 10pods/cpu, I'm wondering how we could change this value when a cluster is started ?"

According to the openshift team, such limit can be managed using this parameter

"this limit can be changed in the node configuration, see: https://docs.openshift.com/container-platform/3.7/admin_guide/manage_nodes.html#admin-guide-max-pods-per-node
Looking at https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#configuration it seems that the configuration file should be available under /var/lib/origin/openshift.local.config with oc cluster up. You can use --use-existing-config argument when restarting your cluster to avoid regenerating the configuration."

**Comment by anjannath** [comment]
We need a similar command like `minishift openshift config set --patch` which can patch the master config file in `/var/lib/minishift/openshift.local.config/master/master-config.yaml` we just need to patch the `/var/lib/minishift/openshift.local.config/node-localhost/node-config.yaml` file.

right now there's no value set for it in the `node-config` file:
```yaml
kubeletArguments:
  cgroup-driver:
  - cgroupfs
```

**Comment by LalatenduMohanty** [comment]
I could reproduce this , steps to reproduce
* minishift start --memory 4GB
* deploy the cake-php application
* increase the pods to 20
* you will see that the last pod will go to pending state. If you check the status of the pod you will see `No nodes are available that match all of the following predicates:: Insufficient pods (1).`

**Comment by LalatenduMohanty** [comment]
@anjannath suggested following to patch the node config `minishift openshift config set --target node --patch '{"kubeletArguments": { "max-pods": ["20"] } }`, will get back if it works.

**Comment by LalatenduMohanty** [comment]
> @anjannath suggested following to patch the node config minishift openshift config set --target node --patch '{"kubeletArguments": { "max-pods": ["30"] } }, will get back if it works.

It did not fix the issue for me. Need to dig more.

**Comment by cmoulliard** [comment]
This command was working for me with origin 3.7.1

```
minishift openshift config set --target node --patch '{"kubeletArguments": { "max-pods": ["30"] } }'
Patching OpenShift configuration /var/lib/origin/openshift.local.config/node-localhost/node-config.yaml with {"kubeletArguments": { "max-pods": ["30"] } }
Restarting OpenShift
...
minishift ssh
[docker@demo ~]$ more /mnt/sda1/var/lib/minishift/openshift.local.config/node-localhost/node-config.yaml
allowDisabledDocker: false
apiVersion: v1
authConfig:
  authenticationCacheSize: 1000
  authenticationCacheTTL: 5m
  authorizationCacheSize: 1000
  authorizationCacheTTL: 5m
dnsBindAddress: ""
dnsDomain: cluster.local
dnsIP: 172.30.0.1
dnsNameservers: null
dnsRecursiveResolvConf: ""
dockerConfig:
  dockerShimRootDirectory: /var/lib/dockershim
  dockerShimSocket: /var/run/dockershim.sock
  execHandlerName: native
enableUnidling: true
imageConfig:
  format: openshift/origin-${component}:v3.7.1
  latest: false
iptablesSyncPeriod: 30s
kind: NodeConfig
kubeletArguments:
  cgroup-driver:
  - systemd
  max-pods:
  - "30"
```
