### ISSUE TITLE
Unable to access registry in 1.0.0-beta.1

### ISSUE THREAD

**Issue by chouseknecht** [minishift/minishift#220]
### Issue:

I can expose the registry that comes installed with OpenShift, but the delivered certificates stop me from actually logging into it.  Firstly, the hostname given to the route by `oc expose svc/docker-regsitry` does not match the generated certificate. Secondly, creating a route with the expected hostname results in "x509: certificate signed by unknown authority". 

### Version:
1.0.0-beta.1

### Environment
```
$ minishift version
minishift version: 1.0.0-beta.1

$ minishift start --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-alpha.1/minishift-centos.iso

$ oc login -u system:admin
$ oc adm policy add-cluster-role-to-user cluster-admin developer
$ oc login -u developer -p developer

Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    kube-system
  * myproject
    openshift
    openshift-infra

$ oc project default
Now using project "default" on server "https://192.168.64.2:8443"
```

### Reproduce:

Logged in with the *developer* account and using the *default* project, expose the registry:

```
$ oc expose svc/docker-registry
route "docker-registry" exposed

$ oc get route
NAME              HOST/PORT                                     PATH      SERVICES          PORT       TERMINATION
docker-registry   docker-registry-default.192.168.64.2.xip.io             docker-registry   5000-tcp
```

Now attempt to login:

```
$ docker login https://docker-registry-default.192.168.64.2.xip.io -u developer -p developer
Error response from daemon: Get https://docker-registry-default.192.168.64.2.xip.io/v1/users/: x509: certificate is valid for 192.168.64.2.xip.io, not docker-registry-default.192.168.64.2.xip.io
```

The hostname given to the route does not match the generated certificate, so let's create a route with the expected hostname, 192.168.64.2.xip.io:

```
$ cat registry.yml
apiVersion: v1
kind: Route
metadata:
  name: registry-access
spec:
  host: 192.168.64.2.xip.io
  to:
    kind: Service
    name: docker-registry
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
status:
  ingress:
    -
      host: 192.168.64.2.xip.io
      routerName: router
      conditions:
        -
          type: Admitted
          status: 'True'

$ oc create -f registry.yml
route "registry-access" created
```

Now attempt to login:

```
$ docker login https://192.168.64.2.xip.io -u developer -p developer
Error response from daemon: Get https://192.168.64.2.xip.io/v1/users/: x509: certificate signed by unknown authority
````

**Comment by chouseknecht** [comment]
I was able to resolve this by starting minishift with the following options:

```
minishift start \
    --insecure-registry 172.30.0.0/16  \
    --insecure-registry minishift \
    --iso-url https://github.com/minishift/minishift-centos-iso/releases/download/v1.0.0-alpha.1/minishift-centos.iso
```

And then

- Add an entry to the local /etc/hosts file that associates "minishift" with  `minishift ip`. 
- `oc login -u system:admin`
- `oc adm policy add-cluster-role-to-user cluster-admin developer`
- `oc login -u developer -p developer`
- `oc project default`

Now create a route with a hostname of 'minishift' using the following YAML:

```
~/projects/oc-cluster $ oc adm policy add-cluster-role-to-user cluster-admin developer
apiVersion: v1
kind: Route
metadata:
  name: registry-access
spec:
  host: minishift
  to:
    kind: Service
    name: docker-registry
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
status:
  ingress:
    -
      host: minishift
      routerName: router
      conditions:
        -
          type: Admitted
          status: 'True'
``` 

And finally, login... 

```
docker login https://minishift -u developer -p $(oc whoami -t)
Login Succeeded
```
