### ISSUE TITLE
Provide a empty ImagePolicy to get the default behavior in 3.9

### ISSUE THREAD

**Issue by nicolaferraro** [minishift/minishift#2379]
### General information

Following https://github.com/openshift/origin/issues/19663. It seems there's a change in behavior in current version of Minishift w.r.t. local lookup of image streams.

The `lookupPolicy` field on ImageStreams is ignored in latest version.

As suggested in the linked issue, the config needs to contain:
```
admissionConfig:
  pluginConfig:
    openshift.io/ImagePolicy: {}
```
In order to get the default behavior.

  * Minishift version: `minishift v1.17.0+f974f0c`
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. Follow the steps in https://github.com/openshift/origin/issues/19663

### Expected
Image is first looked up in imagestreams with `lookupPolicy -> local = true` then on docker hub.

### Actual
Image is only looked up on docker hub.

### Logs
N/A

**Comment by nicolaferraro** [comment]
Comparing the config with --openshift-version `3.9.0` and `3.7.1`. I get the following on `3.9.0`:

```
admissionConfig:
  pluginConfig:
    GenericAdmissionWebhook:
      configuration:
        apiVersion: v1
        disable: false
        kind: DefaultAdmissionConfig
      location: ""
```

i.e. no `openshift.io/ImagePolicy`

While with `3.7.1` I get:
```
admissionConfig:
  pluginConfig:
    GenericAdmissionWebhook:
      configuration:
        apiVersion: v1
        disable: false
        kind: DefaultAdmissionConfig
      location: ""
    openshift.io/ImagePolicy:
      configuration:
        apiVersion: v1
        executionRules:
        - ignoreNamespaceOverride: false
          invertMatch: false
          matchDockerImageLabels: null
          matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            set: false
            value: "true"
          matchImageLabels: null
          matchIntegratedRegistry: false
          matchRegistries: null
          name: execution-denied
          onResources:
          - group: ""
            resource: pods
          - group: ""
            resource: builds
          reject: true
          skipOnResolutionFailure: true
        kind: ImagePolicyConfig
        resolutionRules: null
        resolveImages: ""
      location: ""
```
