### ISSUE TITLE
minishift openshift config set --patch doesnt work for setting default project template with Quota

### ISSUE THREAD

**Issue by gbvikas** [minishift/minishift#2453]
### General information

  * Minishift version: minishift v1.17.0+f974f0c .. 3.9
  * OS:  macOS
  * Hypervisor: VirtualBox

### Steps to reproduce

  1.  Create a new project default template using `oc create -f <template-name>`
```
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: default-project-request
objects:
- apiVersion: v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: v1
  kind: ResourceQuota
  metadata: 
    name: ${PROJECT_NAME}-quota
  spec: 
    hard: 
      memory: 1024Mi
      cpu: 500m
      pods: 3
      resourcequotas: 1
- apiVersion: v1
  kind: LimitRange
  metadata: 
    name: ${PROJECT_NAME}-limits
    creationTimestamp: null
  spec: 
    limits: 
      - 
        type: Pod
        max: 
          cpu: 500m
          memory: 750Mi
        min: 
          cpu: 10m
          memory: 5Mi
      - 
        type: Container
        max: 
          cpu: 500m
          memory: 750Mi
        min: 
          cpu: 10m
          memory: 5Mi
        default: 
          cpu: 100m
          memory: 100Mi
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admins
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_ADMIN_USER}
  userNames:
  - ${PROJECT_ADMIN_USER}
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:${PROJECT_NAME}
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${PROJECT_NAME}
  userNames: []
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:builder
- apiVersion: v1
  groupNames: []
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:deployer
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
```

  2. Run below command to patch openshift:
```
minishift openshift config set --patch '{"projectConfig":{"defaultNodeSelector": "","projectRequestMessage":"", "projectRequestTemplate": "default-project-request","securityAllocator":{"mcsAllocatorRange": "s0:/2","mcsLabelsPerProject": 5,"uidAllocatorRange": "1000000000-1999999999/10000"}}}' --target master
```

### Expected

Patching should be successful

### Actual

Patching OpenShift configuration '/var/lib/origin/openshift.local.config/master/master-config.yaml' with 
```
'{"projectConfig":{"defaultNodeSelector": "","projectRequestMessage":"", "projectRequestTemplate": "default-project-request","securityAllocator":{"mcsAllocatorRange": "s0:/2","mcsLabelsPerProject": 5,"uidAllocatorRange": "1000000000-1999999999/10000"}}}'
```
Unable to restart OpenShift after patchting it. Rolling back.
