### ISSUE TITLE
Cannot use imagestream with insecure registry

### ISSUE THREAD

**Issue by rhuss** [minishift/minishift#2730]
### General information

  * Minishift version: minishift v1.23.0+91235ee
  * OS: macOS
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. Start Minishift with an insecure registry

```
minishift start --memory 4192 --insecure-registry some-registry:8888 --vm-driver virtualbox
```

  2. Verify that the Docker Daemon picked it up

```
minishift ssh -- docker info

...

Insecure Registries:
 some-registry:8888
 172.30.0.0/16
 127.0.0.0/8
```

  3. Check that you can pull that image with the internal Docker daemon

```
eval $(minishift docker-env)
docker pull some-registry:8888/fuse7/fuse-ignite-server:1.1-4
Trying to pull repository some-registry:8888/fuse7/fuse-ignite-server ...
1.1-4: Pulling from brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/fuse7/fuse-ignite-server
378837c0e24a: Already exists
e17262bc2341: Already exists
....

```

  4. Create an ImageStream

```yaml
kind: ImageStream
....
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: some-registry:8888/fuse7/fuse-online-server:1.1-4
    generation: 2
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
```

  5. Check Status of image stream

```
status:
  dockerImageRepository: 172.30.1.1:5000/myproject/fuse-online-server
  tags:
  - conditions:
    - generation: 2
      lastTransitionTime: 2018-08-23T07:49:30Z
      message: 'Internal error occurred: Get https://some-registry:8888/v2/:
        http: server gave HTTP response to HTTPS client'
      reason: InternalError
      status: "False"
      type: ImportSuccess
    items: null
    tag: latest
```

### Expected

The Docker image referenced in the imagestream should be pulled with http as the registry is marked as insecure.

### Actual

See above.

**Comment by praveenkumar** [comment]
@rhuss you need to add openshift secret or use https://docs.openshift.com/container-platform/3.9/dev_guide/managing_images.html#insecure-registries for insecure registry in your image stream.

**Comment by rhuss** [comment]
Thanks for the hint, but unfortunately, adding 


```yaml
annotations:
    openshift.io/image.insecureRepository: "true"
```

to the `ImageStream` meta doesn't help (if when the imagestream is recreated).

Still I get 

```
status:
  dockerImageRepository: 172.30.1.1:5000/myproject/fuse-online-operator
  tags:
  - conditions:
    - generation: 2
      lastTransitionTime: 2018-08-23T10:49:56Z
      message: 'Internal error occurred: Get https://some-registry:8888/v2/:
        http: server gave HTTP response to HTTPS client'
      reason: InternalError
      status: "False"
      type: ImportSuccess
    items: null
    tag: "1.4"
```

even when the Docker info yields

```
Insecure Registries:
 some-registry:8888
 172.30.0.0/16
 127.0.0.0/8
```

**Comment by praveenkumar** [comment]
@rhuss Also check https://github.com/minishift/minishift/issues/2544#issuecomment-415413190 , I think we can close this issue as duplicate also.

**Comment by rhuss** [comment]
No, I don't think its a duplicate as its a different issue. I had the issue mentioned in #2544, too and applied the patch (which helped for the whitelisting). 

However, here I already could create the imagestream (with having the registry not whitelisted you couldn't even create the imagestream) but OpenShift still tries to pull the image with https instead of http, despite that I added the annotation mentioned.

**Comment by rhuss** [comment]
> Set the openshift.io/image.insecureRepository annotation to true => which you did
> 
> Each node has Docker configured with the --insecure-registry flag matching the registry part of the dockerImageRepository. See Host Preparation for more information. => that also done
> 
> Each istag specification must have referencePolicy.type set to Local. See Reference Policy for more information => Not done

@praveenkumar  I disagree as https://docs.openshift.com/container-platform/3.9/dev_guide/managing_images.html#insecure-registries says

> The above definition only affects importing tag and image metadata. For this image to be used in the cluster (e.g., to be able to do a docker pull), **one of** the following must be true:
>
> * Each node has Docker configured with the --insecure-registry flag matching the registry part of the dockerImageRepository. See Host Preparation for more information.
>
> * Each istag specification must have referencePolicy.type set to Local. See Reference Policy for more information.

So only either making the daemon pull from insecure registry **or** having local reference policy (in the case when the docker daemon can't pull from insecure registries). This makes sense IMO.

Just not sure whether this is an OpenShift or Minishift issue.

**Comment by praveenkumar** [comment]
@jorgemoralespou any idea if we missed something or this is the openshift behavior?

**Comment by jorgemoralespou** [comment]
@praveenkumar sadly this is one of the differences that OC cluster has with regards to a real cluster. The admissions controllers don't have the correct configuration for reference Local to work. 

Adding @grahamdumpleton as he might be able to give you all the details and the patch command to fix it and a link to the issue if there's one. I know we've discussed this over email.

**Comment by praveenkumar** [comment]
@jorgemoralespou Thanks. that would be helpful.

**Comment by GrahamDumpleton** [comment]
How is the image referenced by the image stream being deployed? The local lookup policy issue is only relevant if using init containers in DeploymentConfig, Deployment, StatefulSet, Jobs, or raw Pod.

**Comment by rhuss** [comment]
It's a standard `DeploymentConfig` however as mentioned I haven't set the referencePolicy of the istags to 'Local' but configured (and ensured) the Docker Daemon to be able to access the insecure registry (verified by a `docker pull`). According to the docs, this should be sufficient.

**Comment by rhuss** [comment]
I will retry later with a local reference policy, too.

**Comment by GrahamDumpleton** [comment]
If using a standard DeploymentConfig, with image in main container and you have appropriate trigger for ImageChange, then should be fine. This looks to be a different issue related to insecure registry and nothing to do with local lookup policy.

**Comment by jorgemoralespou** [comment]
@grahamdumpleton, thanks, I was confused as you always give so much details that I eventually don't understand what you say, so no idea when things are same or different 🤪
That's why I always need you to come in, cause you know the stuff.

**Comment by budhram** [comment]
@rhuss Please let us know your updates here. This would help to keep track of such vital problem and its solution.

**Comment by rhuss** [comment]
@budhram  sorry, I have no further update as I skipped trying it as @GrahamDumpleton mentions that this issue with the insecure registry is not related to the local policy. Regardless what, I consider it already a bug that (a) allowing the Docker daemon access to the insecure registry and (b) using the `openshift.io/image.insecureRepository: "true"` annotation doesn't trigger an insecure pull of the registry. 

So I suggest reproducing this issue with the setup above in order to find out why the annotation doesn't trigger an insecure pull from the registry.

**Comment by gordillo-ramon-redhat** [comment]
@rhuss, I have tried with Local policy, and it works fine. Example:

```
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: some-registry:8888/fuse7/fuse-online-operator:1.2-7
    generation: 2
    importPolicy:
      scheduled: true
      insecure: true 
    referencePolicy:
      type: Local 
    name: "1.5"
```
