### ISSUE TITLE
Spark jobs fail due to permission issue

### ISSUE THREAD

**Issue by skonto** [minishift/minishift#2836]
### General information

  * Minishift version: v3.1.0
  * OS: Linux 
  * Hypervisor: KVM 

Spark jobs on minishift will fail with : 

Driver:
> Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 6, 172.17.0.6, executor 1): java.nio.file.AccessDeniedException: ./spark-examples_2.11-2.5.0-SNAPSHOT.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)

Executor:

> 2018-09-28 12:41:42 INFO  Utils:54 - Fetching spark://spark-pi-1538138492869-driver-svc.spark.svc:7078/jars/spark-examples_2.11-2.5.0-SNAPSHOT.jar to /var/data/spark-318ba0f7-a04d-4ab1-8a87-cd16c583bdad/spark-22ab7c32-9cdd-4957-9f9c-bc1255ef2d99/fetchFileTemp8771422401989726306.tmp
2018-09-28 12:41:42 INFO  Utils:54 - Copying /var/data/spark-318ba0f7-a04d-4ab1-8a87-cd16c583bdad/spark-22ab7c32-9cdd-4957-9f9c-bc1255ef2d99/4973287571538138497170_cache to /opt/spark/work-dir/./spark-examples_2.11-2.5.0-SNAPSHOT.jar
2018-09-28 12:41:42 ERROR Executor:91 - Exception in task 0.0 in stage 0.0 (TID 0)
java.nio.file.AccessDeniedException: ./spark-examples_2.11-2.5.0-SNAPSHOT.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)

Also reported here: https://stackoverflow.com/questions/50477893/file-access-error-running-spark-on-kubernetes

Looks similar to this: https://github.com/minishift/minishift/issues/802

### Steps to reproduce

  1. Start minikube 
eval $(./minishift oc-env)
oc login -u system:admin
eval $(minishift docker-env)
  2.  Use the following rbac rules

```
apiVersion: v1
kind: Namespace
metadata:
  name: spark
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: spark-role-test
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spark-role-binding-test
subjects:
- kind: ServiceAccount
  name: spark-sa
  namespace: spark
roleRef:
  kind: ClusterRole
  name: spark-role-test
  apiGroup: rbac.authorization.k8s.io
```
Launch a job:

```
git clone https://github.com/lightbend/spark
./dev/make-distribution.sh --name test --r --tgz -Psparkr -Phadoop-2.7 -Pkubernetes -Phive
tar -zxvf spark-2.4.0-SNAPSHOT-bin-test.tgz

cd spark-2.4.0-SNAPSHOT-bin-test
./bin/docker-image-tool.sh -r $DOCKER_USERNAME -t $TAG  build

./bin/spark-submit              
 --master k8s://https://<ip>:8443               
--deploy-mode cluster              
 --name spark-pi               
--class org.apache.spark.examples.SparkPi               
--conf spark.executor.instances=1               
--conf spark.kubernetes.namespace=spark               
--conf spark.kubernetes.authenticate.driver.serviceAccountName=spark-sa              
--conf spark.kubernetes.container.image=$DOCKER_USERNAME/spark:$TAG
local:///opt/spark/examples/jars/spark-examples_2.11-2.5.0-SNAPSHOT.jar
 ```
### Expected
Job should run fine as it does when run with the cluster-admin role. Also it runs easily on other envs like GKE with the above resource rules.

### Actual
Job fails. What are the additional imposed restrictions by minishift? I tried to add resources in the rules section but none changes the results.

### Logs
N/A
