### ISSUE TITLE
CertificateSigningRequest: Status.Certificate is nil for approved CSR

### ISSUE THREAD

**Issue by kniels5** [minishift/minishift#2891]
### General information

Minishift version: v1.24.0+8a904
OS: macOS
Hypervisor: VirtualBox (centos)

### Steps to reproduce

  1.  Create the Certificate Signing Request

```
cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  request: $(cat ${certdir}/server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```
  2. Check status of request

```
kubectl get csr mwc-example.mwc-example -o json
```
```
    },
    "status": {
        "conditions": [
            {
                "lastUpdateTime": "2018-10-12T02:15:44Z",
                "message": "This CSR was approved by kubectl certificate approve.",
                "reason": "KubectlApprove",
                "type": "Approved"
            }
        ]
    }
```
### Expected

1. Certificate should be returned at status.certificate

### Actual

1. Certificate is nil/empty

### Logs

Master-Config:
```
controllerConfig:
  controllers:
  - '*'
  election: null
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
controllers: ""
```
I am not sure if this is just a matter of enabling the certificate controller (understanding this should be enabled by default). If I need to enable is there a mechanism to do that after cluster creation

**Comment by anjannath** [comment]
> I am not sure if this is just a matter of enabling the certificate controller (understanding this should be enabled by default). If I need to enable is there a mechanism to do that after cluster creation

@kniels5 This looks like an origin specific question, have you tried asking it in https://github.com/openshift/origin? minishift uses `oc cluster up` to provision the cluster

**Comment by kniels5** [comment]
@anjannath I am running minishift, not sure why this is more appropriate for that forum. Minishift provides ways to configure openshift that are unique to minishift.

**Comment by praveenkumar** [comment]
> Minishift provides ways to configure openshift that are unique to minishift.

@kniels5 minishift uses `oc cluster up` under the hood and if there is some issue with `cluster up` then you might see same issue with minishift also.

**Comment by douglascamata** [comment]
I have the same issue running OC 3.10 in and minishift v1.28.0+48e89ed.

Inside the minishift VM I see that the `kube-controller-manager`is started with empty cluster signing key/cert files even though in `minishift openshift config view --target kube` I can see the `serviceServingCert` section configured correctly. Also the files are present inside the VM.

```bash
$ minishift ssh
$ sudo ps aux | grep 
$ sudo ps aux | grep kube-controller-manager

root      3084  3.1  2.3 521544 95168 ?        Ssl  09:51   3:34 hyperkube kube-controller-manager --enable-dynamic-provisioning=true --use-service-account-credentials=true --leader-elect-retry-period=3s --leader-elect-resource-lock=configmaps --controllers=* --controllers=-ttl --controllers=-bootstrapsigner --controllers=-tokencleaner --controllers=-horizontalpodautoscaling --pod-eviction-timeout=5m --cluster-signing-key-file= --cluster-signing-cert-file= --experimental-cluster-signing-duration=720h --root-ca-file=/etc/origin/master/ca-bundle.crt --port=10252 --service-account-private-key-file=/etc/origin/master/serviceaccounts.private.key --kubeconfig=/etc/origin/master/openshift-master.kubeconfig --openshift-config=/etc/origin/master/master-config.yaml
docker   18655  0.0  0.0   9092   928 pts/0    S+   11:46   0:00 grep --color=auto kube-controller-manager
```

I'm investigating to see what I can find.

**Comment by douglascamata** [comment]
Upgrading to the latest release of minishift (v1.31.0+cfc599c) solved the problem for me.

**Comment by gbraad** [comment]
This means v3.11 of OpenShift fixed this

**Comment by douglascamata** [comment]
I'm not sure if this was an OpenShift issue. I have access to a v3.10 cluster that works well. The plugins there are configured like this: 

```
admissionConfig:
  pluginConfig:
    BuildDefaults:
      configuration:
        apiVersion: v1
        env: []
        kind: BuildDefaultsConfig
        resources:
          limits: {}
          requests: {}
    BuildOverrides:
      configuration:
        apiVersion: v1
        kind: BuildOverridesConfig
    openshift.io/ImagePolicy:
      configuration:
        apiVersion: v1
        executionRules:
        - matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: 'true'
          name: execution-denied
          onResources:
          - resource: pods
          - resource: builds
          reject: true
          skipOnResolutionFailure: true
        kind: ImagePolicyConfig
```

There is no major configuration change between this cluster and the one set up by minishift.
