### ISSUE TITLE
Minishift CertificateSigningRequest created and approved but certificate is not issued.

### ISSUE THREAD

**Issue by Dimss** [minishift/minishift#3290]
### General information

  * Minishift version: minishift v1.33.0+ba29431
  * OS: macOS
  * Hypervisor:xhyve 

### Steps to reproduce
  1.
 ```
cat <<EOF | cfssl genkey - | cfssljson -bare server
{
  "hosts": [
    "my-svc.my-namespace.svc.cluster.local",
    "my-pod.my-namespace.pod.cluster.local",
    "192.0.2.24",
    "10.0.34.2"
  ],
  "CN": "my-pod.my-namespace.pod.cluster.local",
  "key": {
    "algo": "ecdsa",
    "size": 256
  }
}
EOF
```
  2.
```
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
``` 
  3. 
`oc adm certificate approve my-svc.my-namespace`
  4. 

### Expected
`my-svc.my-namespace   1m        system:admin   Approved,Issued`
and 
`Status.Certificate not null`

### Actual
`my-svc.my-namespace   1m        system:admin   Approved`
and 
`Status.Certificate is null`

### Extra 

```
1. openshift ssh
2. ps -ef | grep controller-manager
3. root      5851  5831  4 17:01 ?        00:00:26 hyperkube kube-controller-manager --enable-dynamic-provisioning=true --use-service-account-credentials=true --leader-elect-retry-period=3s --leader-elect-resource-lock=configmaps --controllers=* --controllers=-ttl --controllers=-bootstrapsigner --controllers=-tokencleaner --controllers=-horizontalpodautoscaling --pod-eviction-timeout=5m --cluster-signing-key-file= --cluster-signing-cert-file= --experimental-cluster-signing-duration=720h --root-ca-file=/etc/origin/master/ca-bundle.crt --port=10252 --service-account-private-key-file=/etc/origin/master/serviceaccounts.private.key --kubeconfig=/etc/origin/master/openshift-master.kubeconfig --openshift-config=/etc/origin/master/master-config.yaml
```
The `--cluster-signing-key-file= --cluster-signing-cert-file=` are  empty. 
As per [K8S docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/#kube-controller-manager), the default value for thous flags are 
```
--cluster-signing-key-file string     Default: "/etc/kubernetes/ca/ca.key"
and
--cluster-signing-cert-file string     Default: "/etc/kubernetes/ca/ca.pem"
```
but inside the running  kube-controller-manager  container such folder doesn't exists. 
The config-master.yaml include following configs
```
controllerConfig:
  controllers:
  - '*'
  election: null
  serviceServingCert:
    signer:
      certFile: service-signer.crt
      keyFile: service-signer.key
```

So, finally the question, how to pass the `service-signer.crt` and `service-signer.key` to the kube-controller-manager? 
And why they are not appended to the `kube-controller-manager` startup command with correct values?

**Comment by leyvReyn** [comment]
I have similar problem

**Comment by leyvReyn** [comment]
Workaround that helped me:
1. minishift ssh
2. vi /var/lib/minishift/base/kube-apiserver/master-config.yaml
3. add
```yaml
...
kubernetesMasterConfig:
  apiLevels:
  - v1
  apiServerArguments: null
  controllerArguments:
    cluster-signing-cert-file:
      - /etc/origin/master/ca.crt
    cluster-signing-key-file:
      - /etc/origin/master/ca.key
  disabledAPIGroupVersions: {}
...
```
4. save
5. exit
6. minishift stop && minishift start

`ps -ef | grep controller-manager` still returns 
`--cluster-signing-key-file= --cluster-signing-cert-file=` but CertificateSigningRequest.status.certificate now contains data, and condition contains `Issued`:
`oc get csr admission-webhook-example-svc.default`
NAME                                    AGE       REQUESTOR   CONDITION
admission-webhook-example-svc.default   33s       feda        Approved,Issued
