### ISSUE TITLE
StatefulSet pods can't ping each other

### ISSUE THREAD

**Issue by plord12** [minishift/minishift#3368]
### General information

  * Minishift version: 

```minishift v1.34.1+c2ff9cb```

  * OS: Linux / macOS / Windows

```MacOS 15.15```

  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox / hyperkit

```VirtualBox```

### Steps to reproduce

  1. Start cluster as usual -

```
$ minishift start --cpus=4 --memory=8GB
$ eval $(minishift docker-env)
$ eval $(minishift oc-env)
```

  2. Create a centos yaml file -

```
apiVersion: v1
kind: Service
metadata:
  name: centos
  labels:
    app: centos
spec:
  selector:
    app: centos
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: centos
spec:
  selector:
    matchLabels:
      app: centos
  serviceName: centos
  replicas: 2
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: centos/tools:latest
          tty: true
```

  3.  apply

```
$ oc apply -f centos.yaml 
service/centos created
statefulset.apps/centos created
```

  4. test one pod can ping the other ( well, actually looks like name resolution failure ) -

```
$ oc exec centos-0 ping centos-1.centos.myproject.svc.cluster.local
ping: centos-1.centos.myproject.svc.cluster.local: Name or service not known
command terminated with exit code 2
```

### Expected

Name resolution and ping works between pods. 

I found running the same test passes with docker-desktop, kind and minikube.

### Actual

See above for failure.

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.
