### ISSUE TITLE
Question: default cluster admin user

### ISSUE THREAD

**Issue by kenjones-cisco** [minishift/minishift#402]
I logged in as `oc login -u system:admin` but when attempting to create a new SecurityContextConstraints, I get an error.
```bash
$ oc create -f lessrestricted.yaml
Error from server: error when creating "lessrestricted.yaml": User "system" cannot create securitycontextconstraints at the cluster scope
```

I tried changing `system` to many variations and it allows the login successfully but I'm not able to find a user with the role `cluster-admin` which allows for the creation of a SecurityContextConstraints. I have been able to do it in previous versions of minishift.

Which default user has the `cluster-admin` role?

**Comment by praveenkumar** [comment]
@kenjones-cisco Can you share or paste `lessrestricted.yaml` so we can try out and see what's going on?

**Comment by kenjones-cisco** [comment]
```yaml
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities:
- IPC_LOCK
apiVersion: v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: lessrestricted denies access to all host features and
      SELinux context that are allocated to the namespace.  This is less restrictive than restricted.
  creationTimestamp: null
  name: lessrestricted
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret
```
