### ISSUE TITLE
get `pod failed to fit in any node` on 1.0.0 when deploying an app that works fine on OSO

### ISSUE THREAD

**Issue by jstrachan** [minishift/minishift#862]
Am trying to deploy the openshift template below using
```
oc process --param PROJECT_NAMESPACE=jstrachan-jenkins -f openshift.yml | oc apply -f -
```
and the pod cannot be scheduled:
```
$ oc describe pod jenkins-1-k4nmb
Name:			jenkins-1-k4nmb
Namespace:		myproject-jenkins
Security Policy:	restricted
Node:			/
Labels:			deployment=jenkins-1
			deploymentconfig=jenkins
			group=io.fabric8.fabric8-team-components.apps
			project=jenkins-openshift
			provider=fabric8
			version=3.0-SNAPSHOT
Status:			Pending
IP:
Controllers:		ReplicationController/jenkins-1
Containers:
  jenkins:
    Image:	fabric8/jenkins-openshift:v1a399cc
    Ports:	50000/TCP, 8080/TCP
    Limits:
      cpu:	2
      memory:	1Gi
    Requests:
      cpu:	2
      memory:	1Gi
    Liveness:	http-get http://:8080/login delay=420s timeout=3s period=10s #success=1 #failure=30
    Readiness:	http-get http://:8080/login delay=3s timeout=3s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/lib/jenkins from jenkins-home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from jenkins-token-45jjp (ro)
    Environment Variables:
      PROJECT_NAMESPACE:		jstrachan-jenkins
      KUBERNETES_NAMESPACE:		myproject-jenkins (v1:metadata.namespace)
      GIT_COMMITTER_EMAIL:		fabric8@googlegroups.com
      GIT_COMMITTER_NAME:		fabric8
      OPENSHIFT_ENABLE_OAUTH:		true
      OPENSHIFT_ENABLE_REDIRECT_PROMPT:	true
      KUBERNETES_TRUST_CERTIFICATES:	true
      KUBERNETES_MASTER:		https://kubernetes.default:443
      MAX_METASPACE_SIZE:		200m
      JENKINS_OPTS:			-Dgroovy.use.classvalue=true
      RECOMMENDER_API_TOKEN:		<set to the key 'token' in secret 'jenkins-recommender-api-token'>
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  jenkins-home:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	jenkins-home
    ReadOnly:	false
  jenkins-token-45jjp:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	jenkins-token-45jjp
QoS Class:	Guaranteed
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2m		15s		13	{default-scheduler }			Warning		FailedScheduling	pod (jenkins-1-k4nmb) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (1)
```

Any ideas? This template works fine on OpenShift Online. Am not sure if this is a minishift issue, an openshift issue or the configuration of minishift and/or openshift really. I've tried using 'minishift start' along with starting with 1, 2 or 3 cpus and lots of memory. e.g. my last attempt was:
```
minishift  start --vm-driver=xhyve --memory=8144 --cpus=3 --disk-size=50g
```

Here's the Template YAML if you wanna try it yourself:
```
---
apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
    project: jenkins-openshift
    version: 3.0-SNAPSHOT
    group: io.fabric8.fabric8-team-components.apps
  name: jenkins-openshift
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-docker-cfg
  data:
    config.json: ""
  type: fabric8.io/jenkins-docker-cfg
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-git-ssh
  data:
    ssh-key: ""
    ssh-key.pub: ""
  type: fabric8.io/jenkins-git-ssh
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-hub-api-token
  data:
    hub: ""
  type: fabric8.io/jenkins-hub-api-token
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-maven-settings
  data:
    settings.xml: PHNldHRpbmdzPg0KICA8IS0tIHNldHMgdGhlIGxvY2FsIG1hdmVuIHJlcG9zaXRvcnkgb3V0c2lkZSBvZiB0aGUgfi8ubTIgZm9sZGVyIGZvciBlYXNpZXIgbW91bnRpbmcgb2Ygc2VjcmV0cyBhbmQgcmVwbyAtLT4NCiAgPGxvY2FsUmVwb3NpdG9yeT4ke3VzZXIuaG9tZX0vLm12bnJlcG9zaXRvcnk8L2xvY2FsUmVwb3NpdG9yeT4NCiAgPG1pcnJvcnM+DQogICAgPG1pcnJvcj4NCiAgICAgIDxpZD5uZXh1czwvaWQ+DQogICAgICA8bWlycm9yT2Y+ZXh0ZXJuYWw6KjwvbWlycm9yT2Y+DQogICAgICA8dXJsPmh0dHA6Ly9jZW50cmFsLm1hdmVuLm9yZy9tYXZlbjIvPC91cmw+DQogICAgPC9taXJyb3I+DQogICAgPG1pcnJvcj4NCiAgICAgIDxpZD5qYm9zczwvaWQ+DQogICAgICA8bWlycm9yT2Y+ZXh0ZXJuYWw6KjwvbWlycm9yT2Y+DQogICAgICA8dXJsPmh0dHBzOi8vcmVwb3NpdG9yeS5qYm9zcy5vcmcvbmV4dXMvY29udGVudC9yZXBvc2l0b3JpZXMvdGhpcmRwYXJ0eS1yZWxlYXNlcy88L3VybD4NCiAgICA8L21pcnJvcj4NCiAgPC9taXJyb3JzPg0KDQogIDwhLS0gbGV0cyBkaXNhYmxlIHRoZSBkb3dubG9hZCBwcm9ncmVzcyBpbmRpY2F0b3IgdGhhdCBmaWxscyB1cCBsb2dzIC0tPg0KICA8aW50ZXJhY3RpdmVNb2RlPmZhbHNlPC9pbnRlcmFjdGl2ZU1vZGU+DQoNCiAgPHNlcnZlcnM+DQogICAgPHNlcnZlcj4NCiAgICAgIDxpZD5sb2NhbC1uZXh1czwvaWQ+DQogICAgICA8dXNlcm5hbWU+YWRtaW48L3VzZXJuYW1lPg0KICAgICAgPHBhc3N3b3JkPmFkbWluMTIzPC9wYXNzd29yZD4NCiAgICA8L3NlcnZlcj4NCiAgICA8c2VydmVyPg0KICAgICAgPGlkPm5leHVzPC9pZD4NCiAgICAgIDx1c2VybmFtZT5hZG1pbjwvdXNlcm5hbWU+DQogICAgICA8cGFzc3dvcmQ+YWRtaW4xMjM8L3Bhc3N3b3JkPg0KICAgIDwvc2VydmVyPg0KICAgIDxzZXJ2ZXI+DQogICAgICA8aWQ+b3NzLXNvbmF0eXBlLXN0YWdpbmc8L2lkPg0KICAgICAgPHVzZXJuYW1lPjwvdXNlcm5hbWU+DQogICAgICA8cGFzc3dvcmQ+PC9wYXNzd29yZD4NCiAgICA8L3NlcnZlcj4NCiAgPC9zZXJ2ZXJzPg0KDQogIDxwcm9maWxlcz4NCiAgICA8cHJvZmlsZT4NCiAgICAgIDxpZD5uZXh1czwvaWQ+DQogICAgICA8cHJvcGVydGllcz4NCiAgICAgICAgPGFsdERlcGxveW1lbnRSZXBvc2l0b3J5PmxvY2FsLW5leHVzOjpkZWZhdWx0OjpodHRwOi8vY29udGVudC1yZXBvc2l0b3J5L2NvbnRlbnQvcmVwb3NpdG9yaWVzL3N0YWdpbmcvPC9hbHREZXBsb3ltZW50UmVwb3NpdG9yeT4NCiAgICAgICAgPGFsdFJlbGVhc2VEZXBsb3ltZW50UmVwb3NpdG9yeT5sb2NhbC1uZXh1czo6ZGVmYXVsdDo6aHR0cDovL2NvbnRlbnQtcmVwb3NpdG9yeS9jb250ZW50L3JlcG9zaXRvcmllcy9zdGFnaW5nLzwvYWx0UmVsZWFzZURlcGxveW1lbnRSZXBvc2l0b3J5Pg0KICAgICAgICA8YWx0U25hcHNob3REZXBsb3ltZW50UmVwb3NpdG9yeT5sb2NhbC1uZXh1czo6ZGVmYXVsdDo6aHR0cDovL2NvbnRlbnQtcmVwb3NpdG9yeS9jb250ZW50L3JlcG9zaXRvcmllcy9zbmFwc2hvdHMvPC9hbHRTbmFwc2hvdERlcGxveW1lbnRSZXBvc2l0b3J5Pg0KICAgICAgPC9wcm9wZXJ0aWVzPg0KICAgICAgPHJlcG9zaXRvcmllcz4NCiAgICAgICAgPHJlcG9zaXRvcnk+DQogICAgICAgICAgPGlkPmNlbnRyYWw8L2lkPg0KICAgICAgICAgIDx1cmw+aHR0cDovL2NlbnRyYWw8L3VybD4NCiAgICAgICAgICA8cmVsZWFzZXM+PGVuYWJsZWQ+dHJ1ZTwvZW5hYmxlZD48L3JlbGVhc2VzPg0KICAgICAgICAgIDxzbmFwc2hvdHM+PGVuYWJsZWQ+dHJ1ZTwvZW5hYmxlZD48L3NuYXBzaG90cz4NCiAgICAgICAgPC9yZXBvc2l0b3J5Pg0KICAgICAgPC9yZXBvc2l0b3JpZXM+DQogICAgICA8cGx1Z2luUmVwb3NpdG9yaWVzPg0KICAgICAgICA8cGx1Z2luUmVwb3NpdG9yeT4NCiAgICAgICAgICA8aWQ+Y2VudHJhbDwvaWQ+DQogICAgICAgICAgPHVybD5odHRwOi8vY2VudHJhbDwvdXJsPg0KICAgICAgICAgIDxyZWxlYXNlcz48ZW5hYmxlZD50cnVlPC9lbmFibGVkPjwvcmVsZWFzZXM+DQogICAgICAgICAgPHNuYXBzaG90cz48ZW5hYmxlZD50cnVlPC9lbmFibGVkPjwvc25hcHNob3RzPg0KICAgICAgICA8L3BsdWdpblJlcG9zaXRvcnk+DQogICAgICA8L3BsdWdpblJlcG9zaXRvcmllcz4NCiAgICA8L3Byb2ZpbGU+DQogICAgPHByb2ZpbGU+DQogICAgICA8aWQ+cmVsZWFzZTwvaWQ+DQogICAgICA8cHJvcGVydGllcz4NCiAgICAgICAgPGdwZy5leGVjdXRhYmxlPmdwZzwvZ3BnLmV4ZWN1dGFibGU+DQogICAgICAgIDxncGcucGFzc3BocmFzZT5teXNlY3JldHBhc3NwaHJhc2U8L2dwZy5wYXNzcGhyYXNlPg0KICAgICAgPC9wcm9wZXJ0aWVzPg0KICAgIDwvcHJvZmlsZT4NCiAgPC9wcm9maWxlcz4NCiAgPGFjdGl2ZVByb2ZpbGVzPg0KICAgIDwhLS1tYWtlIHRoZSBwcm9maWxlIGFjdGl2ZSBhbGwgdGhlIHRpbWUgLS0+DQogICAgPGFjdGl2ZVByb2ZpbGU+bmV4dXM8L2FjdGl2ZVByb2ZpbGU+DQogIDwvYWN0aXZlUHJvZmlsZXM+DQo8L3NldHRpbmdzPg0K
  type: fabric8.io/secret-maven-settings
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-recommender-api-token
  data:
    token: ${RECOMMENDER_API_TOKEN}
  type: fabric8.io/jenkins-recommender-api-token
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-release-gpg
  data:
    trustdb.gpg: ""
    pubring.gpg: ""
    gpg.conf: ""
    secring.gpg: ""
  type: fabric8.io/jenkins-release-gpg
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-ssh-config
  data:
    config: ""
  type: fabric8.io/jenkins-ssh-config
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 16c4a5afeb3900f883b738d36c642da0fa955853
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/jenkins-openshift
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/icon.svg
      fabric8.io/git-branch: changes
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-tag: fabric8-team-components-1.0.0
    labels:
      project: jenkins
      provider: fabric8
      expose: "false"
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: jenkins-openshift
      provider: fabric8
      group: io.fabric8.fabric8-team-components.apps
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 16c4a5afeb3900f883b738d36c642da0fa955853
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/jenkins-openshift
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/icon.svg
      fabric8.io/git-branch: changes
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-tag: fabric8-team-components-1.0.0
    labels:
      project: jenkins
      provider: fabric8
      expose: "false"
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-jnlp
  spec:
    ports:
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      project: jenkins-openshift
      provider: fabric8
      group: io.fabric8.fabric8-team-components.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-home
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins-mvn-local-repo
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 16c4a5afeb3900f883b738d36c642da0fa955853
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins-openshift&var-version=3.0-SNAPSHOT
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/jenkins-openshift
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/icon.svg
      fabric8.io/git-branch: changes
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
      fabric8.io/scm-tag: fabric8-team-components-1.0.0
    labels:
      fabric8.io/type: preview
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins
  spec:
    replicas: 1
    selector:
      project: jenkins-openshift
      provider: fabric8
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 16c4a5afeb3900f883b738d36c642da0fa955853
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins-openshift&var-version=3.0-SNAPSHOT
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
          fabric8.io/scm-url: http://github.com/fabric8io/fabric8-team-components/jenkins-openshift
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-team-components/master/jenkins-openshift/src/main/fabric8/icon.svg
          fabric8.io/git-branch: changes
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-team-components.git/jenkins-openshift
          fabric8.io/scm-tag: fabric8-team-components-1.0.0
        labels:
          provider: fabric8
          project: jenkins-openshift
          version: 3.0-SNAPSHOT
          group: io.fabric8.fabric8-team-components.apps
      spec:
        containers:
        - env:
          - name: PROJECT_NAMESPACE
            value: ${PROJECT_NAMESPACE}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GIT_COMMITTER_EMAIL
            value: fabric8@googlegroups.com
          - name: GIT_COMMITTER_NAME
            value: fabric8
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "true"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: MAX_METASPACE_SIZE
            value: 200m
          - name: JENKINS_OPTS
            value: -Dgroovy.use.classvalue=true
          - name: RECOMMENDER_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: jenkins-recommender-api-token
          image: fabric8/jenkins-openshift:v1a399cc
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - /var/lib/jenkins/pre-shutdown.sh
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 420
            timeoutSeconds: 3
          name: jenkins
          ports:
          - containerPort: 50000
            name: slave
          - containerPort: 8080
            name: http
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-home
            readOnly: false
        serviceAccountName: jenkins
        volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      provider: fabric8
      project: jenkins-openshift
      version: 3.0-SNAPSHOT
      group: io.fabric8.fabric8-team-components.apps
    name: jenkins
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: jenkins
parameters:
- name: PROJECT_NAMESPACE
- name: RECOMMENDER_API_TOKEN
```
