### ISSUE TITLE
hostPath not allowed in templates

### ISSUE THREAD

**Issue by mazzy89** [minishift/minishift#879]
This is my `DeploymentConfig` which is part of my template

```yaml
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: "${NAME}"
  spec:
    replicas: 1
    selector:
      name: "${NAME}"
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: "${NAME}"
        name: "${NAME}"
      spec:
        containers:
        - env: []
          image: "${IMAGE}"
          volumeMounts:
          - mountPath: /home/app
            name: vol-app
          livenessProbe:
            httpGet:
              path: "${PROBE}"
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: minishift-demo
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: "${PROBE}"
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
        volumes:
        - name: vol-app
          hostPath:
            path: /Users/me/app
    triggers:
    - type: ConfigChange
```

when I try to deploy this template I got an error:

`Error creating: pods "server-2-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]`

Any resolution on this?
