### ISSUE TITLE
Wrong permission in pod when local dir is mounted

### ISSUE THREAD

**Issue by mazzy89** [minishift/minishift#889]
I'm running an application in minishift which mount a folder located under `/Users` in a pod. The folder is automatically mounted when the VM starts. The folder /Users is already mounted in the VM. In the template configuration I have the following config:

```yaml
containers:
        - env: []
          image: "${IMAGE}"
          livenessProbe:
            httpGet:
              path: "${PROBE}"
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: minishift-demo
          volumeMounts:
          - mountPath: /usr/src
            name: app-volume
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: "${PROBE}"
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
        volumes:
        - name: app-volume
          hostPath:
            path: "${APP_VOLUME}"
```

where `APP_VOLUME` is set to something like `/Users/me/my-app`. The problem is that when the Nodejs app starts inside the container it fails because it tries to create some files in that folder. The image has been created locally with this Dockerfile

```Dockerfile
FROM node:7.10.0

WORKDIR /usr/src

EXPOSE 8080

CMD ["npm", "start"]
```

and pushed to the minishift registry. I'm running the VM on Virtualbox in MacOS
